### ISSUE TITLE
Only works on one-to-one of which was to be many-to-many, webrtc

### ISSUE THREAD

**Issue by thebestclass** [webrtc/testrtc#105]
I am developing a conference style application (many-to-many) for video calls this style: [http://spaceify.net/talk/][1]. He even is available on **GitHub** but I can not for my nodejs to work, which is not much novelty, hence I decided to create my own using **PHP** that never leaves me.

I created the server using **WebSockets**, is simple he receives the message and forwards it to all connected .. Just that, nothing more nothing less.

But my problem is that it does not connect with more than one person, to connect with the third person other streams fail. You can only connect one-to-one.

I do not know consider whether the error is in JavaScript or some need to improve server .. What can I do to make it connect to all who come?

See my code:

    var socket = new WebSocket('ws://127.0.0.1:1805/');
    var stunServer = "stun.l.google.com:19302";
    var localStream = null;
    var peerConn = null;
    var started = null;
    var mediaConstraints = {
        'mandatory': {
            'OfferToReceiveAudio': true,
            'OfferToReceiveVideo': true
        }
    };
    
    function createPeerConnection() {
        var servers = [];
        servers.push({
            'url': 'stun:' + stunServer
        });
        var pc_config = {
            'iceServers': servers
        };
        peerConn = new webkitRTCPeerConnection(pc_config);
        peerConn.onicecandidate = function(event) {
            if (event.candidate) {
                sendMessage({
                    type: 'candidate',
                    label: event.candidate.sdpMLineIndex,
                    id: event.candidate.sdpMid,
                    candidate: event.candidate.candidate
                });
            }
        };
        peerConn.onaddstream = function(event) {
            console.log("Added remote stream");
            $("body").append('<video width="320" height="240" autoplay="true" src="' + window.URL.createObjectURL(event.stream) + '"></video>');
        };
        peerConn.onremovestream = function(event) {
            console.log("Remove remote stream");
        };
    }
    
    function sendMessage(message) {
        var mymsg = JSON.stringify(message);
        console.log("SEND: " + mymsg);
        socket.send(mymsg);
    }
    
    function connect() {
        if (localStream) {
            console.log("Creating PeerConnection.");
            createPeerConnection();
            console.log('Adding local stream...');
            peerConn.addStream(localStream);
            started = true;
            peerConn.createOffer(setLocalAndSendMessage, null, mediaConstraints);
        }
    }
        
    socket.addEventListener("message", function(evt) {
        console.log("RECEIVED: " + evt.data);
        processSignalingMessage(evt.data);
    }, false);
    
    function processSignalingMessage(message) {
        var msg = JSON.parse(message);
        if (msg.type === 'offer' && localStream && !started) {
            started = true;
            createPeerConnection();
            console.log('Adding local stream...');
            peerConn.addStream(localStream);
            peerConn.setRemoteDescription(new RTCSessionDescription(msg));
            console.log("Sending answer to peer.");
            peerConn.createAnswer(setLocalAndSendMessage, null, mediaConstraints);
        } else if (msg.type === 'answer') {
            peerConn.setRemoteDescription(new RTCSessionDescription(msg));
        } else if (msg.type === 'candidate') {
            var candidate = new RTCIceCandidate({
                sdpMLineIndex: msg.label,
                candidate: msg.candidate
            });
            peerConn.addIceCandidate(candidate);
        }
    }
    
    function setLocalAndSendMessage(sessionDescription) {
        peerConn.setLocalDescription(sessionDescription);
        sendMessage(sessionDescription);
    }
    
    function startVideo() {
        try {
            navigator.webkitGetUserMedia({
                audio: true,
                video: true
            }, successCallback, errorCallback);
        } catch (e) {
            navigator.webkitGetUserMedia("video,audio", successCallback, errorCallback);
        }
    
        function successCallback(stream) {
            $("body").append('<video width="320" height="240" autoplay="true" src="' + window.URL.createObjectURL(stream) + '"></video>');
            localStream = stream;
        }
    
        function errorCallback(error) {
            console.log('An error occurred: [CODE ' + error.code + ']');
        }
    }

full code here: http://pastebin.com/3iWDLU9Y

  [1]: http://spaceify.net/talk/

**Comment by KaptenJansson** [comment]
This is not the place for these kinds of reports, please use https://groups.google.com/forum/#!forum/discuss-webrtc for this.
