### ISSUE TITLE
TestRTC currently does not run on Firefox 39

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/testrtc#109]
The titlebar and terms and privacy is rendered but the testsuite is not populated.

"This appears to be Firefox" adapter.js:43:3
ReferenceError: parseUrlParameters is not defined main.js:68:4
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create webcomponents-lite.js:1953:6
TypeError: suite.addTest is not a function main.js:39:2
ReferenceError: reportFatal is not defined

**Comment by KaptenJansson** [comment]
@andresusanopinto

**Comment by jgsacris** [comment]
I am still having this problem on Firefox 42 when I run the version from the repository. Any updates on this?

**Comment by jgsacris** [comment]
After doing some testing I found that you can, as a workaround, listen to the "WebComponentsReady" event of the window object and call the addTest inside the event handler.

**Comment by KaptenJansson** [comment]
Strange, test.webrtc.org works fine but not when running locally, maybe a race condition somewhere.

**Comment by KaptenJansson** [comment]
Works fine when polymerized but not when running the raw source.

**Comment by KaptenJansson** [comment]
Could you confirm that it works after using grunt build? That's the case for me at least and we are probably not going to commit in support the non polymerized version.

**Comment by KaptenJansson** [comment]
Ping

**Comment by KaptenJansson** [comment]
Closing due to age.
