### ISSUE TITLE
make a npm module for videoframechecker and microphone

### ISSUE THREAD

**Issue by fippo** [webrtc/testrtc#121]
I would like to use some things from this, in particular the videoframechecker
https://github.com/webrtc/testrtc/blob/master/src/js/camresolutionstest.js#L318
and the mictest
https://github.com/webrtc/testrtc/blob/master/src/js/mictest.js#L48

Can you publish them on npm?
One module without a main so it allows requiring just what I want would be awesome.

@KaptenJansson this could improve the "is video flowing" tests in the samples by testing it actually flows

**Comment by KaptenJansson** [comment]
I will look into this.

**Comment by Pentiado** [comment]
I'm interested in this too but when I looked in code it's not that easy to accomplish it. Tests are depending on globals that are flying around and everything is closely tied to views. What I need is basically a convenient way to run those tests in my project.
I started working on separating tests logic from views and globals and I expect to have it done somewhere near end of November (yes, I work on it only in free time). By running one method you're going to be able start separate test or all of them within test group (camera, microphone etc), you'll be notified about progress through events and in the end you'll report object.

**Comment by KaptenJansson** [comment]
I'm currently working on passing the test object to the tests themselves which will reduce the globals uses (setTestFinished, reportError etc).

**Comment by KaptenJansson** [comment]
Forgot to write, contributions are welcome and highly appreciated ;) Looking forward to review your future PR's.

**Comment by KaptenJansson** [comment]
FYI all tests now have the test object passed directly to it, they are also refactored to constructors with prototype functions. Next inline is call.js.

**Comment by KaptenJansson** [comment]
This is done, right @fippo ?
