### ISSUE TITLE
Use/Check for enumerateDevices instead of calling gUM on page load

### ISSUE THREAD

**Issue by nils-ohlmeier** [webrtc/testrtc#123]

**Comment by KaptenJansson** [comment]
Hi,

I do see the benefit of this in one way but most tests need gUM anyway hence we feel we might as well get the permissions before the start button is pressed.

**Comment by nils-ohlmeier** [comment]
Hi,

I think their are a couple of points to be made here:
- As Sam pointed out here https://developers.google.com/web/updates/2015/10/media-devices enumerateDevices() is the standard according to the specs and getSources() is Chrome specific
- Using a recent version of adapter.js should make it easy to use enumerateDevices() from the shim and stay compatible with older versions of Chrome (<47)
- I find it akward that I get a gUM permission prompt when loading test.webrtc.org with Firefox and then indicators the page is using my camera, but I don't see anything using it.

I think enumerateDevices() at page load would not cause a permission prompt or indicators and then calling gUM once the user clicks "Start" would make a lot more sense to the average user.

There is interest in getting testrtc compatible with/for Firefox, and this is one of the bigger blockers.

**Comment by KaptenJansson** [comment]
I do see the issue for Firefox users due to it not having sticky HTTPS permissions (.i.e it asks for permissions everytime regardless of protocol).

I will take a look and see how it will pan out.

**Comment by KaptenJansson** [comment]
I took another look at this and I do not see any benefits of using enumerateDevices instead.

We are using the current mechanism to make sure we are in a state where getUserMedia will most likely succeed and not to present the user with a test page that will fail with gUM denied error without explicit warning (if you decline or it fails gUM permissions you have the option to report a bug or continue without). We are not using the camera or microphone at this point, we do stop the streams but yes, both Chrome and Firefox leave the media indicators to show that permission to the devices has been given, however these indicators cannot tell the user if they are in use or not, in Chrome there is a red light for this and Firefox displays a floating icon when media devices are in use.

Using enumerateDevices we can infer permissions by checking that the device label property is `!== ''`. Do you want to only request gUM on page load if the device label is `=== ''` or just when pressing the start button? What is the benefit?

Also, could you elaborate why this is a blocker for Firefox?

**Comment by KaptenJansson** [comment]
Btw, I've now fixed remaining blockers for Firefox, all tests shall now work on both Chrome and Firefox.

**Comment by KaptenJansson** [comment]
@nils-ohlmeier ping.
