### ISSUE TITLE
Allow testing without going through a relay

### ISSUE THREAD

**Issue by jessetane** [webrtc/testrtc#124]
I understand why this is not the default, but it would be nice to be able to specify a STUN url explicitly in the user interface.

**Comment by KaptenJansson** [comment]
Have you tried entering STUN address in the TURN section in the settings?

**Comment by jessetane** [comment]
I have. This is where the STUN url appears to be getting stripped out:

https://github.com/webrtc/testrtc/blob/8cd64c6fb5664519e9c0ec97f708aae02caa139b/src/js/conntest.js#L49

**Comment by KaptenJansson** [comment]
Right, I guess this is because if we use STUN the tests will not be very realistic as it would loopback just outside the router and back in again while connecting to a turn server simulates a real scenario where the user is located somewhere else.

**Comment by KaptenJansson** [comment]
But sure, if there is a need, PR's are welcome, also I can take a look and see if it works.

**Comment by jessetane** [comment]
Ok thanks, I'll take a look

**Comment by jessetane** [comment]
fixed by #127
