### ISSUE TITLE
WebRTC Troubleshooter results are not all green

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#126]
Steps to Reproduce: 
1. Go to https://test.webrtc.org
2. Click on 'Start' option
3. Wait for the results

Expected Result: The results showed be seen as the green check marks

Actual Result: I am seeing the red 'X' mark for the audio capture under the 'Microphone' section.  
The link to the test report is as follows:
https://test.webrtc.org/report/AMIfv96B3-ki31YuEWfWvk7MQawUje6Xh_e_Q_F8ZOs069iIxVCXdFFs-RmIQlOV88utWYR6O5bCxT2sEs6lF5_vph7fF8jqqzgp5-HF4GxPogLpnQ2tWMckejv2qFtkzAoOywBskGMO_6hGjY_Nhet10aefvwe4pw

**Comment by selavazhagan** [comment]
![screenshot 2015-10-02 at 9 55 12 am](https://cloud.githubusercontent.com/assets/9001606/10252350/c84639a4-68eb-11e5-906a-91d353860747.png)

**Comment by KaptenJansson** [comment]
According to the report, the microphone does not work, have you tried a loopback call in apprtc?

**Comment by selavazhagan** [comment]
Tried again after a page change, i do see the red x mark for the relay connectivity and Data throughput. The screenshot is attached with the error seen on the js console
![screenshot 2015-10-16 at 3 36 16 pm](https://cloud.githubusercontent.com/assets/9001606/10554838/fed93f94-741b-11e5-81c7-6dbda93b6d95.png)

**Comment by selavazhagan** [comment]
In the build 47.0.2526.25/7520.17.0 dev in Squawks, i do see the results as follows, so not sure, exactly what should be expected in the results in the new page, so i have added the screenshot here.
![screenshot 2015-10-20 at 10 32 41 am](https://cloud.githubusercontent.com/assets/9001606/10615868/0cba3d5e-7717-11e5-8987-5fbe1b1944a7.png)

**Comment by tednakamura** [comment]
Closing per offline discussion. Basically, this bug has jumped around from initially reporting a microphone problem, to relay connectivity and data throughput, to only relay connectivity. If any of those specific issues crops up again, we'll file a more specific issue.
