### ISSUE TITLE
Network, Connectivity, Throughput tests not running in WebRTC troubleshooter page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#142]
Steps to reproduce:
1. Navigate to https://test.webrtc.org
2. Click on ' Start' button

Actual results:
Network, Connectivity and Throughput tests do not run.
JS console throws an error "Uncaught TypeError: Cannot read property 'optional' of null"

Expected results:
Network, Connectivity and Throughput tests should run

**Comment by KaptenJansson** [comment]
Thanks for reporting!

I think there are two issues here, one is that when the Turn sever is not responding the JS error above is thrown or responding with 400. In the cases where it does not respond I see the JS error mentioned above, that's most likely something in the code. I've just refactored those tests but not published that yet. Will test after I've published the new version and see if it fixes the JS issue at least. 

@jiayliu is looking into the CEOD issue.

**Comment by selavazhagan** [comment]
This is observed across most of the devices

**Comment by KaptenJansson** [comment]
A general note, if you see the same error across all test pages in various repos, it's most likely a central issue, i.e. not related to the test page itself rather a shared resource, in this case the CEOD instance which provides Turn servers. Also while fixing the CEOD instance, the Turn servers where reinstalled hence why they were down..

**Comment by KaptenJansson** [comment]
The timed out issue has been fixed in the latest push of TestRTC.
