### ISSUE TITLE
Due to the unavailability of the turn server the trickle-ice test case is failing

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#143]
Steps: 
1. Join a apprtc loopback call to get the information for the turn server and its username and password to enter into the location in the peerconnetion/trickle-ice page

Expected Result:
The details should be seen

Actual Result:
Instead, seeing the error as 'Failed to load resource: the server responded with a status of 400 (OK)'

**Comment by KaptenJansson** [comment]
This is expected if the turn server is down
