### ISSUE TITLE
Apprtc peer to peer and the iframe apprtc calls are not working as intended

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#144]
Steps:
1. Join the two way apprtc call between the device spring and the desktop user

Expected result:
The call should be connected successfully

Actual result:
The call is not getting connected, maybe because of the turn server unavailability

Even the iframe apprtc call also is not getting connected successfully

**Comment by cvranjani** [comment]
Observed the same issue on device jaq.

**Comment by KaptenJansson** [comment]
I think all of these bugs are a symptom of the CEOD and Turn server being down yesterday. Please retest today.

Also this is filed in the wrong repo, this should have been filed in https://github.com/webrtc/apprtc.

**Comment by KaptenJansson** [comment]
Ow I see you used the apprtc iframe test page as well. That belongs here if there is an issue on the iframe apprtc page itself, otherwise it should be reported in the apprtc repo.
