### ISSUE TITLE
File transfer not working on device samus

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#145]
Repro steps:

1. Navigate to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/ 
2. Click on 'Choose file' and select any file for file transfer
3. Observe that 'Choose file' button looks disabled as if file transfer is happening but 'Send progress' and 'Receive progress' remains same and file transfer does not happen on device samus
4. No errors in java script console logs.
"This appears to be Chrome
common.js:8 204.605: Created local peer connection object localConnection
common.js:8 204.606: Created send data channel
common.js:8 204.613: Created remote peer connection object remoteConnection
common.js:8 204.628: Offer from localConnection 
v=0
o=- 6728341857094920197 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:dTHGo1uT83F1VayU
a=ice-pwd:KmCzSjbMKm1U2wklnJcd198T
a=fingerprint:sha-256 B3:21:19:B5:45:59:FE:35:CA:33:76:61:23:61:84:F1:2C:76:1E:AB:79:87:DD:62:D6:11:55:CC:6B:2E:C1:3A
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 204.632: Answer from remoteConnection 
v=0
o=- 8154013111500330321 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:yThJE3quB7t+Bq+t
a=ice-pwd:N/uda+nvhPAW8utohXpLD76A
a=fingerprint:sha-256 B3:21:19:B5:45:59:FE:35:CA:33:76:61:23:61:84:F1:2C:76:1E:AB:79:87:DD:62:D6:11:55:CC:6B:2E:C1:3A
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 204.782: local ice callback
common.js:8 204.783: remote ice callback"

Expected result:
Selected file should be transferred

Actual result:
Selected file is not getting transferred on device samus

**Comment by KaptenJansson** [comment]
I think all of these bugs are a symptom of the CEOD and Turn server being down yesterday. Please retest today.
