### ISSUE TITLE
Frirefox show false negatives on the single resolution webcam test

### ISSUE THREAD

**Issue by jgsacris** [webrtc/testrtc#160]
On camresolutionstest.js on the collectAndAnalyzeStats_ function calling addEventListener on the videoTrack throws an exception since the videoTrack doesn't contain this method. This result in a false negative since the method execution is interrupted as this exception is not catched anywhere.

Tested on Windows Firefox 36.0.1, 39.0 and 42.0 and Mac 42.0

**Comment by KaptenJansson** [comment]
Thanks for reporting.

Looked into this and Firefox does not support event handlers on the MediaStreamTrack object.
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack (check the matrix at the bottom of the page)

@jan-ivar, @fippo FYI.

**Comment by fippo** [comment]
hrm... nightly might. I would expect https://bugzilla.mozilla.org/show_bug.cgi?id=910249 to have fixed this but it's not quite clear in which version.
