### ISSUE TITLE
Microphone tests failing on device Engurade

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#169]
Device: Engurade
Version: 49.0.2600.0 / 7782.0.0 dev

1. Browse to https://test.webrtc.org/ 
2. Click Allow in the getUserMedia prompt
3. Click Start
4. Observe that tests for Microphone -> Audio capture are failing with following error:
"[ OK ] Audio track created using device=Default
[ INFO ] Channel 0 levels: -25.1 dB (peak), -33.3 dB (RMS)
[ INFO ] Channel 1 levels: -76.3 dB (peak), -77.2 dB (RMS)
[ FAILED ] Microphone input level is low, increase input volume or move closer to the microphone.
[ OK ] Active audio input channels: 2
[ INFO ] Stereo microphone detected."

Note: 
Audio setting on device is set to maximum
![img_7732](https://cloud.githubusercontent.com/assets/15255941/12058668/13d643d4-af03-11e5-95cc-87d486052b6b.JPG)

Expected result:
Microphone->Audio capture tests should succeed with out any errors

Actual result:
Microphone->Audio capture test is failing with "[ FAILED ] Microphone input level is low, increase input volume or move closer to the microphone."

Javascript logs:
"https://www.chromestatus.com/features/6750456638341120 for more details.
(index):15984 chrome: {"audio":true,"video":true}
(index):15984 chrome: {"audio":{"optional":[{"echoCancellation":false},{"sourceId":"default"}]}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":320,"maxWidth":320,"minHeight":240,"maxHeight":240}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":640,"maxWidth":640,"minHeight":480,"maxHeight":480}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":720,"maxHeight":720}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":160,"maxWidth":160,"minHeight":120,"maxHeight":120}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":160,"maxWidth":160,"minHeight":120,"maxHeight":120}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":320,"maxWidth":320,"minHeight":180,"maxHeight":180}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":320,"maxWidth":320,"minHeight":240,"maxHeight":240}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":640,"maxWidth":640,"minHeight":360,"maxHeight":360}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":640,"maxWidth":640,"minHeight":480,"maxHeight":480}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":768,"maxWidth":768,"minHeight":576,"maxHeight":576}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1024,"maxWidth":1024,"minHeight":576,"maxHeight":576}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":720,"maxHeight":720}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":768,"maxHeight":768}}}
(index):15984 chrome: {"audio":false,"video":{"mandatory":{"minWidth":1280,"maxWidth":1280,"minHeight":800,"maxHeight":800}}}"

**Comment by KaptenJansson** [comment]
It could be the sensitivity of the microphone is lower on this device, if you make some noise while performing the test it should pass. Note that this is not a critical failure, should probably make this failure as a warning as well.

**Comment by cvranjani** [comment]
Retrying this test scenario on device Engurade is now displaying a warning instead of failure:
![img_7852](https://cloud.githubusercontent.com/assets/15255941/12097974/dc037fa6-b2d3-11e5-8649-ae0cd23943c3.JPG)

"[ OK ] Audio track created using device=Default
[ INFO ] Channel 0 levels: 0.0 dB (peak), 0.0 dB (RMS)
[ WARN ] Clipping detected! Microphone input level is high. Decrease input volume or move away from the microphone.
[ INFO ] Channel 1 levels: 0.0 dB (peak), 0.0 dB (RMS)
[ WARN ] Clipping detected! Microphone input level is high. Decrease input volume or move away from the microphone.
[ OK ] Active audio input channels: 2
[ INFO ] Stereo microphone detected."
