### ISSUE TITLE
Mic/Camera tests fail in Linux

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#170]
Steps to reproduce:
1. Open the Troubleshooter page https://test.webrtc.org/ in Linux 14.04
2. Click "Start" to run the tests

Expected results:
All tests should pass

Actual results:
Mic and Camera (resolution 320x240) tests fail (reproducible 8/10 times)
Report - https://test.webrtc.org/report/AMIfv94266zp9bKB31Qyu5rOr2vF8Xis26mIG-7HzLtvB90-a2AMviSWsDOoTlFk9rwOiEc5mKJkwDlD1xDkKRiGtG5RNy7nwnfB_oCkVb3-BT6eKilbmVJat4I0ejfWn0f2NqINUg4AiZRbFYKwIy07Ri1LuIjulQ

Testenv - Chrome 49.0.2622.0 / Linux 14.04
Screenshot below

![screenshot from 2016-01-15 11 16 07](https://cloud.githubusercontent.com/assets/14947786/12368519/f087a4f4-bba0-11e5-8981-ff966beb4bcc.png)

**Comment by srnarayanan** [comment]
I know for sure this worked yesterday in Chrome 49.0.2621.0
I re-ran the test in 49.0.2621.0 today and it failed! (I get the same errors)

**Comment by KaptenJansson** [comment]
Please check your microphone in an https://appr.tc/?debug=loopback call.

WRT to the camera failure the camera is slow hence triggering the onmute event and then followed onmute. Really need to change the onmute event as a warning.
