### ISSUE TITLE
Uncaught error in js logs after clicking on window that is selected for screen capture( using Windows picker extension)

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#175]
Chrome Version : 49.0.2623.23 / 7834.9.0 dev
Device: Alex

What steps will reproduce the problem?

On the device Alex:
0. Open a new window (for example: google search) and reduce the size of the window (do not minimize the window)
1. Browse to https://test.webrtc.org/manual/peer2peer/ in a different window
2. Click 'Screen capture' and if you get an error, follow the instructions and install the extension.
3. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
4. After clicking on 'Screen capture',observe that window opened in step 0 is shown under options for available windows.
5. Select window opened in step 0 for screen sharing
6. Observe that the selected window is shown in local preview on left side of https://test.webrtc.org/manual/peer2peer/page
7. Now open the window that is selected for screen sharing and observe that javascript logs show "Uncaught Error: [object MediaStream] MediaStreamTrack.onmute event has fired, no frames to the track.printHandler_ @ main.js:1116error_ @ main.js:1103stream.getVideoTracks.onmute @ main.js:989"

Note:
1. This issue is reproducible 70-80% of the times. Sometimes this issue leads to chrome crash as described in https://code.google.com/p/chromium/issues/detail?id=576477
2. This issue is observed only on device Alex

Javascript console logs:
"This appears to be Chrome
main.js:1118 Requesting doGetUserMedia: constraints: {"audio":false,"video":{"mandatory":{"chromeMediaSource":"desktop","chromeMediaSourceId":"H2m0xMWqjl7AHCafh0NqvQ==","maxWidth":1280,"maxHeight":800}}}
adapter.js:32 chrome: {"audio":false,"video":{"mandatory":{"chromeMediaSource":"desktop","chromeMediaSourceId":"H2m0xMWqjl7AHCafh0NqvQ==","maxWidth":1280,"maxHeight":800}}}
main.js:1118 getUserMedia success
main.js:1116 Uncaught Error: [object MediaStream] MediaStreamTrack.onmute event has fired, no frames to the track.printHandler_ @ main.js:1116error_ @ main.js:1103stream.getVideoTracks.onmute @ main.js:989
main.js:1118 [object MediaStream] MediaStreamTrack.onunmute event has fired."

**Comment by KaptenJansson** [comment]
Closing due to age.
