### ISSUE TITLE
Standard macbook on standard internet not working

### ISSUE THREAD

**Issue by silviapfeiffer** [webrtc/testrtc#177]
WebRTC works perfectly fine for me. However, the report is all red (except for the video camera).
Does the codebase need updating for lastest Google Chrome?

https://test.webrtc.org/report/AMIfv94SVfr3V4ahg7it0ncOADsl1Kq2SYs4qorMQr0lrHiJHcqXRqlCAoyG1_MOEyaJAZR34eEvUSAwwf1g-D-s7XtDTwKiPh1WSVmt72ECd6dDIBe_qM-fZuixP05ezAW5F7yVRihDaNfcsEl6Holax5p2pyZ-kw

**Comment by silviapfeiffer** [comment]
Further information: The console shows:
Failed to load resource: the server responded with a status of 400 (OK) 
when trying to use https://computeengineondemand.appspot.com/turn?username=1234&key=5678
which would explain the connectivity issues.

**Comment by KaptenJansson** [comment]
Hi,

Your microphone is either muted, in a state where it does not capture audio or Chrome is not able to use the microphone for some other reason (getUserMedia succeeds though).

WRT to the other tests that are failing, they rely on being able to get a turn/stun server from https://computeengineondemand.appspot.com/turn?username=1234&key=5678 which is used for the tests, failing to do so will result in an instant failure.

If you browse to https://computeengineondemand.appspot.com/turn?username=1234&key=5678 directly in your browser, do you see a JSON response with server information (username, password, server etc)?

**Comment by silviapfeiffer** [comment]
My microphone was doing fine - it worked in a call I made just before it and another one I made just after it.

The JSON from the computeengine app was first:
{"message": "Instance not yet ready, please try again.", "error": "AppError"}

A second later, I got:
{"username": "1454404880:1234", "password": "kTTD5Unnlih5v99TIaM49uK25t8=", "uris": ["turn:104.155.231.43:3478?transport=udp", "turn:104.155.231.43:3478?transport=tcp", "turn:104.155.231.43:3479?transport=udp", "turn:104.155.231.43:3479?transport=tcp"]}

OK, so now network and connectiviy have gone yellow, so that's good.
That microphone issue is strange though.

**Comment by KaptenJansson** [comment]
Yes, it can be a bit flaky. We are planning on replacing it soonish with a more reliable service.

Hmm, yes it is indeed strange with the microphone, unfortunately there is not a whole lot of info available in Javascript in these cases. All we can see is that the mediaStream feed into WebAudio sends 0 size audio samples. This means getUserMedia succeeds (we are allowed access and the device should be sending audio samples) however when we analyze them in WebAudio, they are all 0 energy.

Could you check if the correct microphone is selected via the options menu (right next to the bug icon and start button on the WebRTC troubleshooter page)?

**Comment by KaptenJansson** [comment]
Ping

**Comment by silviapfeiffer** [comment]
More recently, it has worked for me again, so closing this.
