### ISSUE TITLE
bunch of "Uncaught (in promise)" JS errors in troubleshooter page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#178]
Steps to reproduce:
1. Open https://test.webrtc.org/ in Win 8 Chrome M50 Canary 50.0.2640.0
2. Click "Start" to run the tests 

Actual results:
Just when the "Throughput -> Video Bandwidth" tests start, I see a bunch of Uncaught (in promise) JS errors (as seen in screenshot below)

Link to report - https://test.webrtc.org/report/AMIfv96zztR8XR7FAqQe7HzA61mS0fg3qsizToalosh6RK3wQTmhMnaPwLw5LpOg7ezRcxf-S6qIcKJ6RqqHKHcPa60hpWaSRnNZ2pljocf3qxzHIC6Qm5qz8FFczXatJ7hW07c0cXJ9326ZzKTWWS4cclmDYu29vg

Logs attached
[testrtc-2016-02-04T23-04-12.705Z.log.zip](https://github.com/webrtc/testrtc/files/118409/testrtc-2016-02-04T23-04-12.705Z.log.zip)

![uncaught in promise errors](https://cloud.githubusercontent.com/assets/14947786/12832769/0c118662-cb51-11e5-8904-f5c736be0512.png)

**Comment by srnarayanan** [comment]
Saw this in today's canary 50.0.2641.0 in Mac as well

**Comment by cvranjani** [comment]
Observed this issue on Chrome OS with M50 version  50.0.2655.0 / 7950.0.0 dev

**Comment by KaptenJansson** [comment]
Next time this happens could you attach the logs again from TestRTC and also include the console logging (click on the error to left of the error to expand it).

Thanks!

**Comment by srnarayanan** [comment]
@KaptenJansson - I've attached logs from TestRTC to the original bug report above, when I filed it. Please let us know if that's sufficient. 

In the JS console, I expand the error messages, and I see this 

Uncaught (in promise) Failed to set local offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set local video description recv parameters..
(anonymous function) @ (index):362

Uncaught (in promise) Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..(anonymous function) @ (index):362
