### ISSUE TITLE
Bitrate for Audio codec(Opus, iSAC16k )  in peer connection audio only call is falling to 10 on device Sentry

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#190]
Chrome version: 50.0.2661.37 / 7978.20.0 dev
Device: Sentry

**Steps to reproduce**

1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/audio/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. For each codec in the dropdown menu and Press 'Call'
4. Observe the bitrate graphs for each codec:
   a. For 'Opus" codec, the Bitrate graph shows values ranging between 10 and 30 kbps 
   (not in the expected range of values)
  b. For 'iSAC 16k' codec, the Bitrate graph shows values ranging between 10 and 15 kbps
   (not in the expected range of values)
  c. For G722 codec, the Bitrate graph shows values ranging around 70kbps
  d. For PCMU codec, the bitrate graph shows values ranging around 70kbps
5. Observe that the Packets sent per second graph shows nonzero values.
[webrtc_internals_dump (3).txt](https://github.com/webrtc/testrtc/files/178849/webrtc_internals_dump.3.txt)

Expected results:
Opus:
Bitrate range: ~40 kbps
Packets sent per second range: ~50 packets

iSAC 16k
Bitrate range: ~30 kbps
Packets sent per second range: ~35 packets

G722
Bitrate range: ~70 kbps
Packets sent per second range: ~50 packets

PCMU
Bitrate range: ~70 kbps
Packets sent per second range: ~50 packets

Actual results:
Opus:
Bitrate range: 10-30 kbps
Packets sent per second range: ~50 packets
![bitrate for opus](https://cloud.githubusercontent.com/assets/15255941/13864344/f4b9ee9a-ec5d-11e5-83ee-e0538e58754b.jpeg)

iSAC 16k
Bitrate range: 10-15kbps
Packets sent per second range: ~35 packets
![bitrate for isac16k](https://cloud.githubusercontent.com/assets/15255941/13864346/f8cda3f0-ec5d-11e5-89b1-058eeacc5d37.jpeg)

G722
Bitrate range: ~70 kbps
Packets sent per second range: ~50 packets
![bitrate ofr g722](https://cloud.githubusercontent.com/assets/15255941/13864349/fdc5fccc-ec5d-11e5-83e7-1d5f3574d94d.jpeg)

PCMU
Bitrate range: ~70 kbps
Packets sent per second range: ~50 packets
![bitrate for pcmu](https://cloud.githubusercontent.com/assets/15255941/13864354/033e25ee-ec5e-11e5-90e2-2c30c6a5421f.jpeg)

**Comment by tednakamura** [comment]
Since this appears to be specific to this device, it should probably be tracked in crbug.com. Let's talk about this some more when you're available today.

**Comment by cvranjani** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=596098
