### ISSUE TITLE
Uncaught error in javascript logs during youtube video screenshare using windows picker extension

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#192]
Chrome version: 51.0.2686.0 / 8097.0.0 dev
Device: Falco-li

**Steps to reproduce**
0. Browse to https://test.webrtc.org/manual/peer2peer/
1. Click screen capture and if you get an error, follow the instructions and install the extension.
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Follow the instructions on the page
4. After installing the extension, click on 'Screenshare'
5. Select a window with youtube video and click on 'Share' option at the bottom
6. Observe the shared youtube video is shown in "Local preview" section of https://test.webrtc.org/manual/peer2peer/ page. But video pauses in between and javascript logs show 
" Uncaught Error: [object MediaStream] MediaStreamTrack.onmute event has fired, no frames to the track.printHandler_ @ main.js:1119error_ @ main.js:1106stream.getVideoTracks.onmute @ main.js:865"

Expected results:
Youtube video selected for screensharing should be captured and visible in the extension with good quality and there should not be any pauses in the video play

Actual results:
Youtube video selected for screensharing is captured and visible in the extension but video is pausing in between and javascript logs shows " Uncaught Error: [object MediaStream] MediaStreamTrack.onmute event has fired, no frames to the track.printHandler_ @ main.js:1119error_ @ main.js:1106stream.getVideoTracks.onmute @ main.js:865"
[Falco_js_logs_peer2peer_youtube_video_share.txt](https://github.com/webrtc/testrtc/files/185045/Falco_js_logs_peer2peer_youtube_video_share.txt)

Notes:
1. This issue is seen in M50 and only on some chrome devices such as Daisy, Big , Blaze, Gnawty and Winky
2. This issue is reproducible 50%
3.  Please see this video for bug description:
https://drive.google.com/file/d/0B_iIlDy84LyFamU0OWw1anFtTjg/view?usp=sharing
4. Observed pausing of youtube video screenshare during hangouts also. Bug filed for this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=594290

jansson@:
Please confirm if "onmute event has fired" errors in javascript logs are expected when video is paused.

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by KaptenJansson** [comment]
I think this is a performance issue where as playing a youtube clip while screensharing is too performance taxing for those machines causing the onmute event to  fire (the mediastreamtrack does not receive video frames from the camera).

The bug here is that we should handle the event, i.e. it should not be an uncaught exception.

**Comment by KaptenJansson** [comment]
same as #175
