### ISSUE TITLE
Bandwidth test doesn't ramp up

### ISSUE THREAD

**Issue by stefanholmer** [webrtc/testrtc#193]
I tried https://test.webrtc.org today and noticed that the video bandwidth test never ramped up. Looking at webrtc-internals, it looks like that test doesn't create any video streams at all.

**Comment by KaptenJansson** [comment]
![testrtc video bandwidth](https://cloud.githubusercontent.com/assets/5872605/14491745/fdb8d998-017a-11e6-9b55-92512883e8d1.png)

To me it looks like it's working.

**Comment by KaptenJansson** [comment]
FYI please upload/download a bug report next time and add the link/file here.

**Comment by stefanholmer** [comment]
Works for me too now.

**Comment by KaptenJansson** [comment]
Please file a new ticket if it happens again with the files asked for in my previous comment.
