### ISSUE TITLE
Is this browser side only? Is it possible to use this on my website to test connectivity with turn servers?

### ISSUE THREAD

**Issue by fuub** [webrtc/testrtc#201]
If yes, is there any documentation?

ty

**Comment by KaptenJansson** [comment]
Yes this can be used to check turn server connectivity, but it needs to run in a supported browser (currently Chrome and Firefox). Also it's built upon google app engine but you can decouple the tests and integrate them into your website without using any of the UI bits.

You can find the main documentation [here](https://github.com/webrtc/testrtc/blob/master/README.md) and dev documentation [here](https://github.com/webrtc/testrtc/blob/master/test/README.md).

The tests themselves live [here](https://github.com/webrtc/testrtc/tree/master/src/js).
