### ISSUE TITLE
Ability to dynamically test bandwidth limits in a non-loopback call

### ISSUE THREAD

**Issue by tednakamura** [webrtc/testrtc#203]
https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/ was published earlier today as a result of discussion in [this discuss-webrtc](https://groups.google.com/d/msg/discuss-webrtc/u7k1_hASS4Q/YIZiORhKMAAJ) thread. That sample page uses a loopback call; would it be possible to incorporate similar functionality into the peer2peer page? Well, I'm not dead set on using the peer2peer page, but I'd like there to be some way to easily and dynamically test bandwidth limits in a 2 party non-loopback call.

**Comment by KaptenJansson** [comment]
Should be fairly straight forward but the page itself (if we use peer2peer) needs a refactor and cleanup.

**Comment by KaptenJansson** [comment]
Closing due to age.
