### ISSUE TITLE
Uncaught InvalidAccessError in troubleshooter page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#207]
**Browsers and versions affected**
First seen in Windows 7, Chrome Canary 52.0.2730.0

**Description**
Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
thrown while running tests in https://test.webrtc.org/

**Steps to reproduce**
1. Open https://test.webrtc.org/ and click Start
2. Have an eye on the JS console for any errors

**Expected results**
No JS errors should be seen, and all tests should pass

**Actual results**
main.js:11 Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
onStopCollectingAudio @ main.js:11
e @ main.js:1
g @ main.js:1
collectAudio @ main.js:11

**Comment by srnarayanan** [comment]
it is not reproducible 100% though
@KaptenJansson

**Comment by KaptenJansson** [comment]
Will take a look in a couple of weeks.

**Comment by srnarayanan** [comment]
Saw this issue again in M54 54.0.2840.8 in Win 7

![unnamed](https://cloud.githubusercontent.com/assets/14947786/18186120/c9cf7ac0-7055-11e6-953f-988a965c77d3.jpg)

**Comment by KaptenJansson** [comment]
Closing due to age.
