### ISSUE TITLE
Following development/build instructions results in an error during build step.

### ISSUE THREAD

**Issue by wpp** [webrtc/testrtc#208]
**Description**

I've followed the instructions in the ["Development" section of the README]( https://github.com/webrtc/testrtc#development). But end up with an error during the `grunt build` step. I'm not familiar with all the tools involved but afaik I've followed all instructions in the README which should result in a valid build. So there might be a step missing in the README or it is outdated.

**Steps to reproduce**

1. Install node
2. Install npm `sudo npm install npm -g`
3. npm install
4. bower update
5. grunt
6. grunt build

**Expected results**

A successful build

**Actual results**
```
Running "uglify:target" (uglify) task
JS_Parse_Error {
  message: 'Unexpected token: operator (>)',
  filename: 'main.js',
  line: 2376,
...
```

**Additional information**
- grunt-cli v1.2.0
- grunt v0.4.5
- node v6.2.0
- OS X 10.11.4

**Comment by KaptenJansson** [comment]
Sorry for this, the issue that a dependency (adapter.js) is currently using es6 stuff which does not work well for other projects. Will try to fix.

**Comment by KaptenJansson** [comment]
It's fixed since a little while ago and should work.
