### ISSUE TITLE
"GetUserMedia failed with error" message thrown while attempting to share a screen/application

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#219]
**Browsers and versions affected**
M56 Canary 56.0.2905.0 in Ubuntu, Mac

**Description**
Uncaught (in promise) Error: GetUserMedia failed with error: NotFoundError
    at printHandler_ (main.js:1129)
    at error_ (main.js:1116)
    at main.js:881
message thrown while attempting to share a screen/application window 

**Steps to reproduce**
Pre-requisite: Have multiple Chrome tabs, a few applications like terminal window, finder open
1. Open https://test.webrtc.org/manual/peer2peer/
2. Click 'Screen capture' 
3. Click 'Your Entire screen' thumbnail and share
4. Alternatively, navigate to 'Application Window' tab and click on any thumbnail there (terminal window, finder window)
5. Observe the JS console

**Expected results**
No error messages should be thrown, and whatever has been shared should be seen in the 'Local Preview' 

**Actual results**
1. "Uncaught (in promise) Error: GetUserMedia failed with error: NotFoundError" message thrown
2. Whatever has been shared is not seen in the 'Local Preview' 

Screenshot:

![screenshot from 2016-10-31 13 03 28](https://cloud.githubusercontent.com/assets/14947786/19870055/1f084a5e-9f6c-11e6-96f9-931a2c2684e7.png)

CC: @KaptenJansson

**Comment by srnarayanan** [comment]
Sharing Chrome tabs is successful, and the above error is not seen

**Comment by cvranjani** [comment]
This issue is also observed on chrome OS with 55.0.2883.33 / 8872.31.0 beta

**Comment by cvranjani** [comment]
This issue is seen only when "Application window" is shared using windows picker extension and is not observed with Desktop capture extension

**Comment by KaptenJansson** [comment]
@cvranjani could copy and paste the getUserMedia constraints from chrome://webrtc-internals for when sharing `Application Window` using the `Windows picker` and the `Desktop capture extension`?

**Comment by cvranjani** [comment]
getUserMedia constraints from chrome://webrtc-internals for "Windows Picker" extension:

Caller origin: https://test.webrtc.org
Caller process id: 18050
Audio Constraints
{deviceId: {exact: ["Ng1Fpb9naBpNI6PSAINeQg=="]}, mediaStreamSource: {exact: ["desktop"]}}
Video Constraints
{width: {max: 1366}, height: {max: 768}, deviceId: {exact: ["Ng1Fpb9naBpNI6PSAINeQg=="]}, mediaStreamSource: {exact: ["desktop"]}}

getUserMedia constraints from chrome://webrtc-internals for "Desktop capture" extension:

Caller origin: chrome-extension://bkdbakhchencophomlalidheidibcncj
Caller process id: 18251
Audio Constraints
{deviceId: {exact: ["AZlGmqHnUXH/3Xg7JczW8A=="]}, mediaStreamSource: {exact: ["desktop"]}}
Video Constraints
{width: {max: 1366}, height: {max: 768}, deviceId: {exact: ["AZlGmqHnUXH/3Xg7JczW8A=="]}, mediaStreamSource: {exact: ["desktop"]}}
[Desktop_Capture_Extension_sender_webrtc_internals_dump.txt](https://github.com/webrtc/testrtc/files/564661/Desktop_Capture_Extension_sender_webrtc_internals_dump.txt)
[Desktop_capture_extension_receiver_webrtc_internals_dump.txt](https://github.com/webrtc/testrtc/files/564662/Desktop_capture_extension_receiver_webrtc_internals_dump.txt)

**Comment by KaptenJansson** [comment]
Are these constraints from when you share an application window?

**Comment by cvranjani** [comment]
Yes

**Comment by chenqiang1986** [comment]
I think my change  #223 fixed this issue.

**Comment by KaptenJansson** [comment]
yes and when #222 is merged and served this should go away.

**Comment by KaptenJansson** [comment]
I've now published the new version, please try again.

**Comment by cvranjani** [comment]
Verified this issue on Chrome OS with M57 57.0.2970.0 / 9156.0.0 dev. "Local preview" shows the screen that is shared and there are no js errors.

**Comment by srnarayanan** [comment]
Verified in desktop Chrome with M57 Canary 57.0.2976.0 
No JS errors; sharing "application window" thumbails show up in local preview
