### ISSUE TITLE
Improve timeout on stopCollectingAudio

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/testrtc#23]
It seems collecting audio from a microphone is reasonable flaky to the point one needs to wait 2 seconds to start getting some input from the stream.

Instead of an hard-code timeout of 2 seconds the test should maybe run for as much as 5 seconds terminating as soon as some audio is noticed.. also reporting how long it took to start gathering audio.

**Comment by fsolenberg** [comment]
I'm looking at improving mictest.js; I can take a look at this issue.

**Comment by KaptenJansson** [comment]
Perfect!

**Comment by KaptenJansson** [comment]
Keep in mind this [issue](https://github.com/webrtc/testrtc/issues/30) while doing it (ScriptProcessor is being deprecated).

**Comment by KaptenJansson** [comment]
Fixed in #42
