### ISSUE TITLE
Test Execution hangs on network section

### ISSUE THREAD

**Issue by remy44** [webrtc/testrtc#230]
**Browsers and versions affected**
Chrome & Firefox

**Description**
Test hans after Microphone & Camera test within Network section.
No errors visible on user interface nor browser console

**Steps to reproduce**
This happen on Windows 7 workstation on my customer site.
Any ports different than 80&443  are blocked for outgoing / incoming transfer.

**Expected results**
Network tests results

**Actual results**
No network tests results, neither connectivity

Link to the test result.
No STUN/TURN servers provided:
https://test.webrtc.org/report/AMIfv978xojiVJ15LKFOsTmLHZC7-goFnB4LJHohGE9q41k7G19iD2PlRHwhhO4YIBOysHxkpdhPUItK0aTKN1N9fGDSZ_YM2iwvlb7_pp4RZ0ldmUTNQSZtaIBl3paEDD0WzfJNMki0Ld6hMvIkFg2vyKk6qEpW-w

My own STUN/TURN servers provided )
https://test.webrtc.org/report/AMIfv95ZnIscjkg_afHJ-AOs3n0u6KqNTIb0CK4KB-wCzZhxRUQueyb1cu-idIb8e8UPdTxdSc7wUgR4-IRYWzaQnQu6IZr5w7NBPqOvQd452JVs-b6qNsrTluiPu5vmi-937A97wSBl4kFwzNerl1_K63BBUlBJig

**Comment by remy44** [comment]
![ss](https://cloud.githubusercontent.com/assets/9008109/26344834/45ded488-3fa1-11e7-89f1-829678cf5fed.png)

**Comment by KaptenJansson** [comment]
Thanks for reporting, it will receive some general attention shortly, will look into it.

**Comment by KaptenJansson** [comment]
Same as #211
