### ISSUE TITLE
Publish a public npm module for testrtc

### ISSUE THREAD

**Issue by ajmacd** [webrtc/testrtc#236]
Have you considered publishing publicly on npm to ease ingestion for downstream users? I couldn't find it on npmjs.org and it looks like you've set it to publish privately.

**Comment by KaptenJansson** [comment]
No we have not considered that. Submodules like SSIM and framechecker are published via the https://github.com/webrtc/utilities repo.

**Comment by KaptenJansson** [comment]
Closing due to age.
