### ISSUE TITLE
Bandwidth test section of report full of zeros

### ISSUE THREAD

**Issue by jhillyerd** [webrtc/testrtc#242]
**Browsers and versions affected**

Repros on Chrome 61.0.3163.79, both win32 and linux x86_64

**Steps to reproduce**

1. Visit https://test.webrtc.org/
2. Click Start
3. Wait for tests to finish
4. Click bug
5. Download report

**Expected results**

The following fields with have valid values derived from the results of the test:

{"info":"Send bandwidth estimate average: 0 bps"}},
{"info":"Send bandwidth estimate max: 0 bps"}},
{"info":"Send bandwidth ramp-up time: Infinity ms"}},
{"info":"RTT average: 0 ms"}},
{"info":"RTT max: 0 ms"}},
{"info":"Lost packets: null"}},

**Actual results**

All values are 0/infinity/null

**Comment by jhillyerd** [comment]
Sample log
[testrtc-2017-09-14T19-48-09.289Z.txt](https://github.com/webrtc/testrtc/files/1304379/testrtc-2017-09-14T19-48-09.289Z.txt)

**Comment by KaptenJansson** [comment]
Should work now.
