### ISSUE TITLE
404 of manual test suit

### ISSUE THREAD

**Issue by xjsXjtu** [webrtc/testrtc#244]
**Browsers and versions affected**

Chrome 60.0.3112.113

**Steps to reproduce**

click "audio-and-video" of manual tests":
 * https://test.webrtc.org/manual/audio-and-video/

**Expected results**
 show the test page.

**Actual results**
404 Not Found.
Other manual test suits have the same issue.

**Comment by KaptenJansson** [comment]
The test pages has been moved to https://webrtc.github.io/test-pages/.
