### ISSUE TITLE
Relay and Host connectivity tests failing in the first run of WebRTC troubleshooter tests on chrome devices

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#248]
**Browsers and versions affected**
Chrome: 63.0.3239.37/ 10032.29.0 dev
Chrome devices : Wolf, Sanppy

**Steps to reproduce**
1. Browse to https://test.webrtc.org/ 
2. Click Allow in the getUserMedia prompt
3. Click Start

**Expected results**
All tests should pass
Some failures may be expected, such as:
-if your camera can't support higher resolutions
-if you're currently on a network that doesn't supply an IPv6 address

**Actual results**
- Host connectivity tests fails with "[Failed] Timed out" error 
- Throughput test stops after "data throughput"
- No errors in javascript console
![screenshot 2017-11-06 at 1 55 09 pm](https://user-images.githubusercontent.com/15255941/32469755-07bcd48e-c309-11e7-91cd-03a6f18d2678.png)
[testrtc-2017-11-06T21_57_44.391Z.log](https://github.com/webrtc/testrtc/files/1448142/testrtc-2017-11-06T21_57_44.391Z.log)

Note: This issue is not observed after refreshing https://test.webrtc.org/  page and rerunning the tests

**Comment by cvranjani** [comment]
@KaptenJansson 
@rantonysamy

**Comment by rantonysamy** [comment]
Will check and get back to you.

**Comment by KaptenJansson** [comment]
Network related I believe. Closing.
