### ISSUE TITLE
Test not working on  Firefox 57

### ISSUE THREAD

**Issue by giordanocardillo** [webrtc/testrtc#250]
**Browsers and versions affected**
Mozilla firefox 57

**Steps to reproduce**
Run a test

**Expected results**
Test passing (all are passing on Chrome)

**Actual results**
Could not gather stats: TypeError: Argument 1 of RTCPeerConnection.getStats does not implement interface MediaStreamTrack, on webcam tests.

**Comment by rantonysamy** [comment]
Can I get any exact URL (which test is not working), I will try the same.
