### ISSUE TITLE
Hi Team,

### ISSUE THREAD

**Issue by chuckwilliams10** [webrtc/testrtc#251]
**Browsers and versions affected**

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by chuckwilliams10** [comment]
Hi Team

For some reason the tool can't access my audio and camera.  I tested fine yesterday and there have been no changes.  Any ideas?

Thanks

**Comment by rantonysamy** [comment]
Can you specify your environment setup in this issue ? Thanks.

**Comment by chuckwilliams10** [comment]
Sorry guys,

There are no issues.  The browser was blocking the access.  All is working.  Thanks for responding back.
