### ISSUE TITLE
Blank page on Firefox 57

### ISSUE THREAD

**Issue by Mannshoch** [webrtc/testrtc#254]
**Browsers and versions affected**
Firefox 57 with a migrated profile. 
Was reproducible on several PCs

**Steps to reproduce**
Open the Website

**Expected results**
Some content

**Current result**
Blank page

**Workaround**
Create a new Firefox Profile

The need to create a new Profile is bad. I wish to tell people what to configure to get it run. Maybe an about:config option is the cause for this.

**Comment by KaptenJansson** [comment]
Not sure how we can fix this if a clean firefox profile works?

**Comment by fippo** [comment]
I wouldn't be surprised if this was caused by https://github.com/webrtc/adapter/issues/730 and media.peerconnection.enabled set to false

**Comment by Mannshoch** [comment]
An Information about this and maybe a howto would be nice. But don't tell people that they do not have the correct browser installed

**Comment by KaptenJansson** [comment]
Closing for now, feel free to submit a PR with fixes if its still an issue.
