### ISSUE TITLE
getUserMedia error in Apprtc iframe page

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#255]
**Browsers and versions affected** :  64.0.3280.5 / 10176.3.0 dev 
Chrome device : Elm

**Steps to reproduce**
1.. Browse to https://webrtc.github.io/test-pages/src/iframe-apprtc/ on Chrome OS device and https://appr.tc/ in another machine(say Linux workstation)
2.  Enter the room name from the first machine on the 2nd machine.
3. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors

**Expected results**
Apprtc call should be connected successfully and there should not be any errors in javascript logs

**Actual results**
After joining the call from Chrome OS device,a  pop-up window is displayed with error message "Failed to get access to local media. Error name was NotAllowedError. Continuing without sending a stream."

[Elm_iframe_apprtc_Call_js_logs.txt](https://github.com/webrtc/testrtc/files/1529209/Elm_iframe_apprtc_Call_js_logs.txt)
Javascript logs displayed following warnings:
"AudioCapture permission has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.
webrtc.github.io/:1 VideoCapture permission has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details"

![screenshot 2017-12-04 at 4 08 26 pm](https://user-images.githubusercontent.com/15255941/33583319-98fc88ac-d90e-11e7-84d2-c9c3115f9edb.png)

**Comment by KaptenJansson** [comment]
Scroll down and use the new and only way to use iframes. The first is kept for legacy and negative testing. @rantonysamy maybe we could add the iframes side by side instead? Also put the working one first?

**Comment by rantonysamy** [comment]
Sure, I will send a fixup for this.

**Comment by KaptenJansson** [comment]
Closing this since it's in the wrong project as well.
