### ISSUE TITLE
Microphone tests fail in the first run of WebRTC troubleshooter tests on chrome devices

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#256]
Browsers and versions affected
Chrome: 64.0.3282.24 / 10176.14.0 dev 

Steps to reproduce

1. Browse to https://test.webrtc.org
2. Click Allow in the getUserMedia prompt
3. Click Start

Expected results
All tests should pass

Actual results:
Microphone test fails with following error: 
"Audio capture
[ OK ] Audio track created using device=Default - Built-in mic
[ FAILED ] No active input channels detected. Microphone is most likely muted or broken, please check if muted in the sound settings or physically on the device. Then rerun the test."

Javascript logs show warning : "main.js:1 An AudioContext in a cross origin iframe must be created or resumed from a user gesture to enable audio output.
(anonymous) @ main.js:1"
![screenshot 2017-12-14 at 12 29 58 pm](https://user-images.githubusercontent.com/15255941/34060447-a4cd5aa2-e198-11e7-9483-70a82ce7ea39.png)

[testrtc-2017-12-14T20_29_47.887Z.log](https://github.com/webrtc/testrtc/files/1564002/testrtc-2017-12-14T20_29_47.887Z.log)

Note: Microphone test succeeds after refreshing the page and rerunning the test

**Comment by KaptenJansson** [comment]
Interesting, I would suspect this would happen on all platforms though.

**Comment by KaptenJansson** [comment]
Same as #261
