### ISSUE TITLE
Camera resolution is not captured by chromebit device

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/testrtc#257]
**Browsers and versions affected**
10176.13.1 / 64.0.3282.24 / Mickey

**Steps to reproduce**
1. Browse to https://test.webrtc.org/ 
2. Click Allow in the getUserMedia prompt
3. Click Start

**Expected results**
All tests should pass
[testrtc-2017-12-18T11_09_29.836Z.log](https://github.com/webrtc/testrtc/files/1567669/testrtc-2017-12-18T11_09_29.836Z.log)
![screenshot 2017-12-18 at 12 15 51 pm](https://user-images.githubusercontent.com/34342420/34103693-ff83108e-e3ed-11e7-910d-c39baa42fd2f.png)
![screenshot 2017-12-18 at 12 16 35 pm](https://user-images.githubusercontent.com/34342420/34103694-ff9ae484-e3ed-11e7-809d-52c3418777b1.png)
![screenshot 2017-12-18 at 12 16 43 pm](https://user-images.githubusercontent.com/34342420/34103695-ffb289c2-e3ed-11e7-90af-1ccada9c06f5.png)
![screenshot 2017-12-18 at 12 16 48 pm](https://user-images.githubusercontent.com/34342420/34103696-ffcaba88-e3ed-11e7-930c-b80c0d0ca4d2.png)

**Actual results**
Camera resolution for Logitech device is failing but actually the camera is capable of those resolution.

**Comment by KaptenJansson** [comment]
Does this happen everytime and with different cameras? Also does the camera work in other pages?

**Comment by vkkkumar** [comment]
Yes this was happening all the time. I am not sure if it was working for any other cameras. I can check again with M66 and update you.

**Comment by rantonysamy** [comment]
Checked with M67 Dev and this is working fine now. can be closed.

**Comment by vkkkumar** [comment]
This issue is working as intended. Thus closing it. 69.0.3497.35
