### ISSUE TITLE
invisible accept button on incoming call

### ISSUE THREAD

**Issue by sgoley** [webrtc/testrtc#260]
**Browsers and versions affected**
Google Chrome is up to date
Version 64.0.3282.186 (Official Build) (64-bit)

**Steps to reproduce**
Intermittant issue appearing on reception of inbound call routed to user

**Expected results**
Accept / Reject button appear on rtc client, able to click accept and be connected to call.

**Actual results**
Call dropdown appears with reject button / mute only.

**Comment by KaptenJansson** [comment]
Incorrect repo.
