### ISSUE TITLE
Audio capture fails in test.webrtc.org

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/testrtc#261]
Build Version: M66 Dev
Devices : Chromebox Panther, Buddy (allinone)

What steps will reproduce the problem?
1.Go to test.webrtc.org
2.Click on the Start button
3.Check all the Peripherals works. 

What is the expected result?
Microphone audio does not work all the time. according to the JS console known issue doc, It must resume (but Its not resuming in) 

What do you see instead?
For USB Headsets : Not working 100% of the time
For 3.5mm Jack Headset: Not working for the first time, works after refreshing the page.
For Bluetooth Headset : Not working 100%. 

Messages:

Audio capture
[ OK ] Audio track created using device=Default - Plantronics .Audio 648 USB: USB Audio:3,0: Mic
[ FAILED ] No active input channels detected. Microphone is most likely muted or broken, please check if muted in the sound settings or physically on the device. Then rerun the test.

in the JS Console:
The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Comment by geniusofthecrowd** [comment]
Chrome 66 Stable release completely breaks this, any timeline for a fix?

**Comment by alvestrand** [comment]
Seems the base cause is this: https://bugs.chromium.org/p/chromium/issues/detail?id=835767

**Comment by xujiandream** [comment]
i got a problem while using webrtc:  When i start to capture audio stream and put it to local audioHtmlElement with getUserMedia.It always failed and i hear nothing,so i send 0 bytes audio stream out. Is any boby give me a tip, i don't understand what caused this?This only happens the first time after a long time without doing webrtc stuff.
