### ISSUE TITLE
Microphone not passing test

### ISSUE THREAD

**Issue by draeder** [webrtc/testrtc#267]
**Browsers and versions affected**
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Mac OSX 10.13.4 (17E202) High Sierra
Apple iMac MNE02LL/A 21.5 Inch, 3.4GHz Intel Core i5, 8GB RAM, 1TB Fusion Drive

**Steps to reproduce**
Browse to https://test.webrtc.org and click "START"

**Expected results**
Microphone should be activated and pass the microphone test.

**Actual results**
Site displays: 
[ OK ] Audio track created using device=Default - Built-in Microphone
[ FAILED ] No active input channels detected. Microphone is most likely muted or broken, please check if muted in the sound settings or physically on the device. Then rerun the test.

Console log shows:
The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ main.js:1

Note that the microphone works for all applications, and other sites such as this one: https://www.onlinemictest.com/

**Comment by jdsandifer** [comment]
I have the same issue. My webcam mic works fine at onlinemictest.com and in Windows recording settings I can see the audio meter move next to it in the list. However, it failed the audio test in RTC.

**Comment by claytron5000** [comment]
I suspect this is actually a problem with Chrome.

**Browsers and versions affected:** 
MacOS 10.14 (18A391)
FireFox 65.0.1 - works as expected
Chrome Version 72.0.3626.121 - does not work, same error as listed above.
