### ISSUE TITLE
Huawei Matebook X Pro Microphone doesn't work

### ISSUE THREAD

**Issue by laroucheyouth** [webrtc/testrtc#272]
**Browsers and versions affected**
specific to huawei matebook x pro in all versions of Chrome, from stable, beta and canary.

**Steps to reproduce**
Try to use any website that uses WebRTC.

**Expected results**
Microphone captures audio

**Actual results**
Microphone is not found or unable to be loaded.
https://test.webrtc.org/report/AMIfv97ha4A8VmoA1_8Uv0OcA2wH7URNQv8UxyPdsZ11lm9ftJbJeGYcgnkLpYquOnEKoCT8bossWXIwbp_CNXIJrZuUNIxQMRJJYKwwun5cTFY8VELBNoPZS_vcZvT4PBE3Q0PydM7C_OKd2Zce0CUUdJ9SQaCt_A

**Comment by fippo** [comment]
@guidou can you take a look?

**Comment by guidou** [comment]
@laroucheyouth Can you file a bug at crbug.com?

**Comment by armax00** [comment]
I believe the report should already exist: crbug/868026

I am not sure though if it is the same issue.

**Comment by armax00** [comment]
@fippo would it be possible for you to continue the discussion in crbug/868026? I would need extra information, for example what happens from the console if you were to directly call navigator.mediaDevices.getUserMedia({audio:true})

**Comment by guidou** [comment]
Closing in favor of https://crbug.com/868026.
