### ISSUE TITLE
Looback test

### ISSUE THREAD

**Issue by andresusanopinto** [webrtc/testrtc#39]
It appears quite a few test scripts want to use a loopback to test... maybe we should have such a test?

**Comment by KaptenJansson** [comment]
Loopback with audio and video displayed to the user?

We already setup loopback in camresolutiontest.js when checking the 3 specific resolutions.

**Comment by andresusanopinto** [comment]
Yes this was to display to the user... it may not belong here at the moment.. but if the plan people copy parts of this tool into their app... I guess they might want to have something like that.

Maybe it should be displaying the loopback/recorded audio when the user pics the camera or so?
Just brainstorming where to get a useful thing for developers to copy.

**Comment by KaptenJansson** [comment]
Closing due to age.
