### ISSUE TITLE
Improve code comments

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/testrtc#45]
To make it easier to reuse testrtc we should make sure all comments are up to date and contain useful information. Also add comments where it's lacking.

**Comment by andresusanopinto** [comment]
I think this is not a very good bug description... not really easily to see what action to take, I think we better achieve it by writing higher quality code and not by sprinkling comments from time to time.

I guess you have a specific comments to fix, but then simply send a pull request. No need to make the processing complex to file a bug saying you are going to fix comments.

**Comment by KaptenJansson** [comment]
It was more of a TODO than anything else ;) But point taken.
