### ISSUE TITLE
Discrepancy in supported camera resolutions

### ISSUE THREAD

**Issue by tednakamura** [webrtc/testrtc#67]
The 1280x720 test failed with "Camera does not support a mandatory resolution: 1280x720
," but the output for "Check supported resolutions" includes the line "Supported 1280x720"
https://test.webrtc.org/report/AMIfv9730AKm3Pen5Cxe2x-WYdshuk5vG7BFi1PaGMGvoPH1oWuWkwdp5NFgoP1s9zfUaiUsO3U3IrzQgXmq4FQkOYbLFSPYdtUp3M9GEW4GpTdIXz1dxx0cNR2RWSvjGqclcabQwVy_cg6jfory875miwvAqU_7KQ

(Also, I'm not sure why the test stopped at that point, but that's probably a separate issue)

**Comment by KaptenJansson** [comment]
Closing due to age.
