### ISSUE TITLE
jscs rules are now stricter

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/testrtc#68]
Do sudo npm update
Then grunt

Running "jscs:src" (jscs) task
Expected indentation of 6 characters at src/js/report.js :
    49 |    // test is doing in the wild.
    50 |    ga('send', {
    51 |       'hitType': 'event',
--------------^
    52 |       'eventCategory': 'Test',
    53 |       'eventAction': status,
Expected indentation of 6 characters at src/js/report.js :
    50 |    ga('send', {
    51 |       'hitType': 'event',
    52 |       'eventCategory': 'Test',
--------------^
    53 |       'eventAction': status,
    54 |       'eventLabel': testName,
Expected indentation of 6 characters at src/js/report.js :
    51 |       'hitType': 'event',
    52 |       'eventCategory': 'Test',
    53 |       'eventAction': status,
--------------^
    54 |       'eventLabel': testName,
    55 |       'nonInteraction': 1
Expected indentation of 6 characters at src/js/report.js :
    52 |       'eventCategory': 'Test',
    53 |       'eventAction': status,
    54 |       'eventLabel': testName,
--------------^
    55 |       'nonInteraction': 1
    56 |    });
Expected indentation of 6 characters at src/js/report.js :
    53 |       'eventAction': status,
    54 |       'eventLabel': testName,
    55 |       'nonInteraction': 1
--------------^
    56 |    });
    57 |  },
Expected indentation of 0 characters at src/js/util.js :
     9 |/* exported arrayAverage, arrayMax, arrayMin */
    10 |
    11 |  // array<function> returns the average (down to nearest int), max and min of
--------^
    12 |  // an int array.
    13 |function arrayAverage(array) {
Expected indentation of 0 characters at src/js/util.js :
    10 |
    11 |  // array<function> returns the average (down to nearest int), max and min of
    12 |  // an int array.
--------^
    13 |function arrayAverage(array) {
    14 |  var cnt = array.length;
>> 7 code style errors found!
Warning: Task "jscs:src" failed. Use --force to continue.

Need to fix errors or adjust the rules..

**Comment by KaptenJansson** [comment]
WDYT we should do? Change the rules or the style?

**Comment by andresusanopinto** [comment]
Fix the style in the code.
