### ISSUE TITLE
Seeing 500 Error while trying to negotiate a call when the other user is not established connection with the peerconnection server completely

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#71]
The logs from the console are as follows:

setLocalDescription success
main.js:1108 Sending message {"candidate":"candidate:855189020 1 udp 2122260223 192.168.1.229 37197 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:855189020 2 udp 2122260222 192.168.1.229 43887 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:855189020 1 udp 2122260223 192.168.1.229 56239 typ host generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:855189020 2 udp 2122260222 192.168.1.229 54695 typ host generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756setLocalAndSendMessage_ @ main.js:915
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:1108 Sending message {"candidate":"candidate:3014729896 1 udp 1686052607 104.135.6.108 60806 typ srflx raddr 192.168.1.229 rport 37197 generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:3014729896 2 udp 1686052606 104.135.6.108 62307 typ srflx raddr 192.168.1.229 rport 54695 generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:3014729896 1 udp 1686052607 104.135.6.108 54127 typ srflx raddr 192.168.1.229 rport 56239 generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:3014729896 2 udp 1686052606 104.135.6.108 50893 typ srflx raddr 192.168.1.229 rport 43887 generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 1 tcp 1518280447 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 2 tcp 1518280446 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 1 tcp 1518280447 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 2 tcp 1518280446 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904

**Comment by selavazhagan** [comment]
The Repro steps for the bug are as follows:

1.  Login to the peerconnection page in user A, using the link http://test.webrtc,org/manual/peer2peer 
2.  Request for the permission to get user media by clicking on 'Request GetUserMedia' and select 'Allow' when asked
3.  Enter the peerconnection server address in the 'Server' section
4.  Click on 'Connect'
5.  Click on 'Add' for the Local Stream in the 'Media streams' section
6.  Meantime, in the user B, follow the steps from 1 to 3
7.  Now, in user A, select 'Negotiate' for negotiating the call
8.  Then in user B, click on 'Connect'
9.  Meantime, the user A, shows the above mentioned error information.

**Comment by KaptenJansson** [comment]
Closing.
