### ISSUE TITLE
The A/V/AV request through 'Request GetUserMedia' returns the error 

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#75]
1. On host A: Browse to http://test.webrtc.org/manual/peer2peer page
2. On host A: Request Audio/Video/AV by clicking on 'Request GetUserMedia

Actual Result: The Error message is seen as follows:
Failed to load resource: the server responded with a status of 404 (OK)
/manual/peer2peer/js/main.js:1108 getUserMedia says: ReferenceError: getUserMedia is not defined

Expected Result: The request should be success and based on the request, the audio or video or both should be functional.

**Comment by KaptenJansson** [comment]
I fixed it by adding back components/ to app.yml and components/webrtc-adapter folder when pushing to GAE. Need to fix it permanently however, should work in the meantime though.
