### ISSUE TITLE
Uncaught Error display when Forced iSAC  is used for the audio only in P2P call

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#86]
1. On host A: Browse to peer2peer, fill in the Force iSAC checkbox, and call (audio only). 
2. On host B: Browse to peer2peer, fill in the Force iSAC checkbox, and call (audio only). 
3. Verify audio is flowing between the hosts. 

Expected Result: The audio should flow between the two users

Actual Result: The audio isn't flowing between the two users instead i see the error message as below:
Uncaught Error: setRemoteDescription

**Comment by selavazhagan** [comment]
Used the build 44.0.2403.8/7077.24.0 beta in Blaze and followed the same steps in the description above, and i am still seeing the issue.

**Comment by KaptenJansson** [comment]
Sorry, I fixed it but have not been able to push it to GAE (Google app engine that serves the web page) due to #89. Will push today.

Next time I will let you know once I've pushed the fix.
