### ISSUE TITLE
Sending message using the SCTP Data channel between two users on two different tabs is not working

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#88]
Objective: Test that it's possible to send a message using SCTP Data Channel between two Hosts

Steps followed:
1. On host A and B: Browse to peer2peer and negotiate a call
2. On host A click on create Data Channel and negotiate again  
3. On host A: type a message in Data Channel field and click on send button

Expected Result:  Verify that Host B received the message in the ""Received on Data Channel"" field 

Actual Result: There is no data exchanged between the two users and there is no error messages seen in the console.  

More Info: Tried with both the M43-43.0.2357.65 (64-bit) on Desktop as well as on M44-44.0.2403.14(7077.11.0)dev on Parrot-freon.  Both of them shows the same behaviour.  It is reproducible.

**Comment by KaptenJansson** [comment]
Hmm strange, it works for me. Could you try again and take a screenshot?

**Comment by selavazhagan** [comment]
Tried with the build 44.0.2403.28/7077.24.0 beta on Blaze and Link, works fine.

**Comment by KaptenJansson** [comment]
Please add a screenshot when you see the error (make sure the console is open as well)

**Comment by selavazhagan** [comment]
Tried today again with the same device(Blaze) and the same build(44.0.2403.28/7077.24.0 beta), and it works fine as expected.  I was able to see the message on the user B from user A.  Since, i am not able to reproduce the issue i am closing this issue.
