### ISSUE TITLE
Firefox failure: this.getUserMediaBasedOnSources_ is not a function

### ISSUE THREAD

**Issue by ploxiln** [webrtc/testrtc#91]
I attempted to view https://test.webrtc.org/ today with Firefox 38.0.5 on OS X 10.10.3. It just shows a blank page.

The following error is in the console:
```
TypeError: this.getUserMediaBasedOnSources_ is not a function                           test.webrtc.org:20:375
```

**Comment by KaptenJansson** [comment]
Thank you for reporting, looks like this happened when I pushed latest version and also updated webrtc-adapter. I will fix this tomorrow.

**Comment by KaptenJansson** [comment]
Sorry for not getting to this yet, will really take a look today.
