### ISSUE TITLE
'Uncaught ReferenceError: CreateIceServer is not defined' is seen while trying to add the ICE Servers

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#92]
1. Go to the page https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Enter the STUN or TURN URI detail
3. Click on Add Server

Expected Result:
The Server should be added 

Actual Result: Instead, seeing the error message as follows:
'Uncaught ReferenceError: CreatIceServer is not defined'

**Comment by KaptenJansson** [comment]
This is a samples bug and therefore should be filed in the samples repo https://github.com/webrtc/samples (look at the URL of the page you are using)
